trainer:
  accelerator: 'gpu'
  devices: [0]
  max_epochs: 500
  log_every_n_steps: 5
  check_val_every_n_epoch: 5
  callbacks:
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: val_loss_epoch
        mode: min
        save_last: true
        filename: "gaitgraph-casia-b-{epoch:02d}-{val_loss_epoch:.2f}"
model:
  backend_name: resgcn-n21-r8
  learning_rate: 0.005
  loss_temperature: 0.01
  embedding_layer_size: 128
  multi_branch: True
  tta: True
data:
  data_path: "/data/casiab"
  # batch_size: 768
  batch_size: 1152
  num_workers: 8
  sequence_length: 60
